### ISSUE TITLE
网站上的地图加载不出来。

### ISSUE THREAD

**Issue by jackchoumine** [gislite/webgis-pub#1]
比如 这个路径下 [OpenLayers-->ZoomToExtent Control](http://webgis.pub/openlayers-zoomtoextent.html) 的地图加载不出来。

这是一个很好的学习ol的资料，万望大佬看看，别让这么好呢教程没了。

**Comment by gislite** [comment]
现在已经修复。 最近教程发布程序进行了较大调整；正好服务器到期进行了迁移；这个过程出现了很多的问题，需要花一些时间修改。
